- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/deploy.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    - role: openstack-volume-snapshot

- hosts: all
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/config.yaml
  gather_facts: true

  roles:
    - role: config-common
    - role: config-docker
    - role: config-couchdb

- hosts: main
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: setup-couchdb-cluster
