# COMP90024 Cluster and Cloud Computing
# Group 5
# Aleksandar Pasquini (912504)
# Amelia Fleischer-Boermans (389511)
# Isaac Daly (1129173)
# Mahardini Rizky Putri (921790)
# Richard Yang (1215150)

- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/deploy-website.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: all
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/config-scale.yaml
  gather_facts: true

  roles:
    - role: config-common
    - role: config-volumes
    - role: set-up-website
