# COMP90024 Cluster and Cloud Computing
# Group 5
# Aleksandar Pasquini (912504)
# Amelia Fleischer-Boermans (389511)
# Isaac Daly (1129173)
# Mahardini Rizky Putri (921790)
# Richard Yang (1215150)
---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /data

couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_cookie: a192aeb9904e6590849337933b000c99
couchdb_port: 5984
couchdb_number_of_nodes: 3
couchdb_container_name: couchdb
