# Volume
---
volumes:
  - vol_name: twt-vol-4-1
    vol_size: 10
  - vol_name: twt-vol-4-2
    vol_size: 60

# Security group
security_groups:
  - name: twt_ssh
    description: 'Security group for SSH access'
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: twt_http
    description: 'Security group for HTTP'
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_group
    description: 'Security group for CouchDB'
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_group
    description: 'Security group for CouchDB'
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_group
    description: 'Security group for CouchDB'
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0
# Instance
instances:
  - name: twt-4
    volumes: ['twt-vol-4-1', 'twt-vol-4-2']

instance_groups: ['worker']
