- name: Install dependencies for Twitter harvester
  become: yes
  pip:
    name: ['tweepy', 'better-profanity', 'afinn', 'emoji', 'couchdb']
    state: latest

- name: Git Clone Repo
  become: yes
  git:
    repo: https://Tankofdoom:tnGd9cqwTMTYC2x@github.com/politiCCCs/twitter_harvester.git
    dest: /home/ubuntu/twitter
    recursive: no
    track_submodules: yesssh
    update: true
    force: true
    accept_hostkey: true
